app = 'simplehook-server'
primary_region = 'ord'

[build]
  dockerfile = 'server/Dockerfile'

[env]
  BASE_URL = 'https://hook.simplehook.dev'
  FRONTEND_URL = 'https://simplehook.dev'
  PORT = '8400'
  RUST_LOG = 'simplehook_server=info'

[processes]
  app = 'simplehook-server'

[http_service]
  internal_port = 8400
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
